import type { Metadata } from "next";
import { CardProvider } from "./context/CartProvider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children:React.ReactNode
}){
  return(
    <html lang="es">
      <body>
        <CardProvider>
          {children}
        </CardProvider>
      </body>
    </html>
  )
}


//esto es el equivalente a app.js


// Adaptar el archivo layout.js
// En lugar de usar _app.js, debes crear el archivo layout.js dentro de la carpeta app. En este archivo, envolverás tu aplicación con el proveedor de contexto CartProvider.

// Estructura de layout.js: